#!/bin/bash
clear
# Colors
GREEN='\e[1;92m'
RED='\e[1;91m'
ORANGE='\e[1;93m'
SKYBLUE='\e[1;94m'
YELLOW='\e[1;33m'
BLUE='\e[01;34m'
VIOLET='\e[1;95m'
DARKGREEN='\e[1;96m'
BLACK='\e[01;30m'
CYAN='\e[01;36m'
WHITE='\e[01;37m'
BGBL='\e[1;30;47m'
loc="/sdcard/RemGaming/system"
loc1="/sdcard/RemGaming"
gamin="/data/data/com.termux/files/usr/bin/gaming"
[ ! -d $loc ] && mkdir -p $loc


# APP LIST TO BE ENABLED/DISABLED
gamelist(){
command="$1 $2 $3 $4"
		$command com.android.chrome
		$command com.android.vending
		$command com.instagram.android
		$command com.facebook.lite
		$command com.google.android.play.games
		$command com.android.youtube
		$command com.whatsapp
		$command org.telegram.messenger
		$command com.snaptube.premium
		$command org.lineageos.updater
		$command com.shopee.id
		$command com.yowhatsapp
		$command com.google.android.apps.youtube.creator
		$command com.google.android.youtube
		$command com.antutu.ABenchMark
		$command org.mozilla.firefox
		$command photo.video.instasaveapp	 
		$command com.revenge.gramophone
		$command com.tubebuddy.tubebuddy_mobile
		$command projekt.substratum
		$command com.franco.kernel
		$command com.keramidas.TitaniumBackup
		$command com.picsart.studio
		$command com.google.android.apps.translate
		$command com.alensw.PicFolder
		$command vul.max
		$command free.vpn.unblock.proxy.turbovpn
		$command ru.zdevs.zarchiver.pro
		$command com.sp.protector.free
		$command com.google.android.GoogleCamera
		$command com.google.android.apps.wallpaper
		$command com.android.email
		$command com.yowhatsapp
		$command mark.via.gp
		$command com.superior.superiorwalls
		$command com.android.contacts
		$command com.adobe.lrmobile
		$command com.dv.adm
		$command com.kiwibrowser.browser
		$command com.facebook.katana
		$command com.google.android.gm
		$command instake.repost.instagramphotodownloader.instagramvideodownloader
		$command dev.hdcstudio.sub4subpaid
		$command com.imaginstudio.imagetools.pixellab
		$command com.antutu.benchmark.full
		$command com.aospextended.aexpapers
		$command cn.gavinliu.snapmod
		$command com.primatelabs.geekbench5
		$command com.aerolla
		$command com.google.android.apps.photos
		$command com.statussaver.wapp
		$command org.lineageos.audiofx
		$command com.mixplorer
		$command ru.zdevs.zarchiver
		$command com.oasisfeng.greenify 
		$command ru.andr7e.deviceinfohw
		$command com.handycloset.android.eraser
		$command org.lineageos.jelly
		$command ru.andr7e.deviceinfohw
		$command com.oasisfeng.greenify
		$command ru.zdevs.zarchiver
		$command ru.andr7e.deviceinfohw
		$command com.handycloset.android.eraser
		$command ru.andr7e.deviceinfohw
		$command com.oasisfeng.greenify
		$command com.google.android.gm
		$command com.facebook.katana
		$command com.google.android.youtube
		$command com.whatsapp
		$command com.futuremark.dmandroid.application
		$command com.intsig.camscanner
		$command com.google.android.apps.docs
		$command com.ryzenrise.intromaker
		$command  com.nexstreaming.app.kinemasterfree
		$command com.facebook.mlite
		$command balti.migrate.flasher
		$command balti.migrate.ng
		$command com.mxtech.videoplayer.pro
		$command com.jio.myjio
		$command splendid.postermaker.designer
		$command cn.wps.moffice_eng
		$command com.hyperionics.avar
		$command com.battlenet.showguide
		$command com.thinkyeah.galleryvault
		$command com.google.android.apps.docs. 
		$command editors.docs
		$command com.intsig.lic.camscanner
		$command com.sk.thumbnailmaker
		$command com.chrome.dev
		$command com.opalastudios.pads
		$command com.rarlab.rar
		$command com.realtechvr.glview
		$command eu.thedarken.sdm
		$command com.sbi.SBIFreedom.Plus
		$command com.android.calculator2
		$command com.android.calendar
		$command com.android.camera2
		$command com.android.documentsui
		$command com.android.fmradio
		$command com.android.gallery3d
		$command com.android.stk
		$command com.android.soundrecorder
		$command ru.andr7e.deviceinfohw
		$command com.myairtelapp
		$command com.sdk.hummingbirdfood.delivery
		$command skynet.cputhrottlingtest
		$command com.smule.singandroid
		$command com.zdivdev.ebook.advbash
		$command com.zdivdev.ebook.bashbegin
		$command com.apkzube.learnpythonpro
		$command com.zdivdev.ebook.scripttool
		$command com.supercell.clashroyale
		$command com.google.android.youtube
		$command org.fdroid.fdroid
		$command idm.internet.download.manager.plus
		$command com.rahul.videoderbeta
		$command com.socialnmobile.dictapps.notepad.color.note
                $command org.schabi.newpipe
 }
loop(){
bash /data/data/com.termux/files/usr/bin/gamingup.sh
}
while [ 1 ];
do

printf "${WHITE} "
[ -f $loc/gamingon ] && gname="${RED} 3. Deactivate Gaming Mode." || gname="${GREEN} 3. Activate Gaming Mode."
printf "\e[1;101m\nAPPLE's GAMING OPTIMIZER\e[0m \n"
printf "\n${SKYBLUE}  1. Disable app    \t ${ORANGE}       2. Enable apps\n $gname\t${VIOLET}4. YourList\n ${YELLOW} 5. Activate/Deactivate \t${CYAN}6. UPDATE${WHITE}\n  7. EXIT\t                ${SKYBLUE}8. Remove Apps\n ${GREEN} 9. Remove Apps from YourList."
echo 
echo
printf "\e[1;96mEnter choice:  ${WHITE} "
read o
clear
if [ "$o" == "x" ]; then
echo "EXITING..."
sleep 2s
exit 1
fi
case $o in
1) printf "\e[1;91mDisabling apps \e[0m \n"
echo
echo "Enter package name / press x to exit: "
read d
while [ "$d" != "x" ]
do 
su -c pm disable $d
echo
printf "Enter package name / press x to exit: "
read d;
done
clear
;;

2) echo "Enabling apps..."
echo
su -c pm list packages -d
echo 
echo "Enter package name / press x to exit: "
read e
while [ "$e" != "x" ]
do 
su -c pm enable $e
echo "Enter package name / press x to exit: "
read e;
done
clear
;;

3) run(){
check="$loc1/APPLIST.txt"
[ ! -f $check ] && echo > $check && echo "com.opera.mini.native" > $check && echo "com.android.chrome" >> $check
check1="$loc1/forcelist.txt"
[ ! -f $check1 ] && echo > $check1 && echo "org.lineageos.snap" > $check1 && echo "com.sbi.SBIFreedomPlus" >> $check1
 if [ ! -f $loc/gamingon ]; then
echo > $loc/gamingon 
gamelist su -c am force-stop
gamelist su -c pm disable
while read line;
do 
su -c pm disable $line
done < $check

while read line;
do 
su -c am force-stop $line
done < $check1
else

gamelist su -c pm enable
while read line;
do 
su -c pm enable $line
done < $check
rm -rf $loc/gamingon
fi
}
spin=( '|' '/' '-' '\' )
spin(){
while [ 1 ]
do
  for i in ${spin[@]}
  do
     echo -ne "${GREEN}\rEXECUTING PROGRAM PLEASE WAIT... ($i)${WHITE}"
     sleep 0.08
  done
done
}
execute(){
   spin &
   pid=$!
   run > /dev/null 2>&1
   kill $pid
   if [ -f $loc/gamingon ]; then
   echo -ne "\r\e[1;101mACTIVATED GAMING MODE\e[0m                        "
   echo -e "\n\n${VIOLET}Hit enter to go back to main menu"
read any
clear
   else
    echo -ne "\r\e[1;101mDEACTIVATED GAMING MODE\e[0m                         "
   echo -e "\n\n${VIOLET}Hit enter to go back to main menu"
read any
clear
   fi
   
}
execute
;;

4) clear
printf "${VIOLET}1. APPLIST\n2. Forcelist\n${WHITE}3. Main Menu\n\nEnter your choice: \n"
read choice
case $choice in
1) while [ 1 ]; do
clear
printf "List of apps in your APPLIST\n\n"
check="$loc1/APPLIST.txt"
printf "${GREEN} "
cat $check
printf "${WHITE} \n\n"
echo "Enter app package name / press x for main menu: "
read pack
if [[ $pack == "x" || $pack == "X" ]]; then
break
else
printf "Are you sure your package name is ${VIOLET} $pack ${WHITE}\n\n"
printf "Press ${GREEN} Y/y for Yes ${WHITE} or Press ${RED} N/n for No \n\n"
read opt
[[ $opt == "Y" || $opt == "y" ]] && echo $pack >> $check && clear && printf "Added ${BLUE} $pack \n" ; 
[[ $opt == "N" || $opt == "n" ]] && clear && echo "Exiting.." ; continue;
printf "${WHITE} \n\n ${GREEN}"
cat $check
printf "${WHITE} \n"
fi
done
clear
;;
2) while [ 1 ]; do
clear
printf "List of apps in your Forcelist\n\n"
check1="$loc1/forcelist.txt"
printf "${GREEN} "
cat $check1
printf "${WHITE} \n\n"
echo "Enter app package name or press x for main menu: "
read pack
if [[ $pack == "x" || $pack == "X" ]]; then
break
else
printf "Are you sure your package name is ${VIOLET} $pack ${WHITE}\n\n"
printf "Press ${GREEN} Y/y for Yes ${WHITE} or Press ${RED} N/n for No \n\n"
read opt
[[ $opt == "Y" || $opt == "y" ]] && echo $pack >> $check1 && clear && printf "Added ${BLUE} $pack \n" ; 
[[ $opt == "N" || $opt == "n" ]] && clear && echo "Exiting.."
printf "${WHITE} \n\n ${GREEN}"
cat $check1
printf "${WHITE} \n"
fi
done
clear
;;
3) clear
continue
;;
esac
;;
7) exit 1
;;
6) rm -rf ~/gaming
cd $HOME
git clone https://github.com/NganDii/gaming
bash ~/gaming/Installer.sh > /dev/null 2>&1
clear
echo -e "${GREEN} Updated Successfully"
echo -e "\n\n${RED} Press Enter to Restart ${WHITE}"
read any
gaming
;;
5) [ -f $loc/gamingon ] && rm -rf $loc/gamingon || echo > $loc/gamingon
;;
8) any="1"
while [ "$any" == "1" ];
do
clear
echo -e "${GREEN}"
grep -n "command" $gamin
echo -e "\n\n${VIOLET}Enter the line number to delete one by one / Press x to go to main menu${WHITE}"
read del
if [[ "$del" == "" ]]; then
echo -e "${RED}Please input something\n${GREEN}Press enter to continue "
read lol
continue
elif [[ "$del" == "x" ]]; then
loop
else
sed -i "${del}d" $gamin
echo -e "\n${RED}Deleted line $del successfully ${WHITE}\n\nPress enter to continue deleting or press x to goto main menu"
read any
if [[ "$any" == "x" ]]; then
loop
else
any=1
fi
fi
done
loop
;;
9) any="1"
while [ "$any" == "1" ];
do
clear
echo -e "${GREEN}"
grep -n "" /sdcard/RemGaming/APPLIST.txt
echo -e "\n\n${VIOLET}Enter the line number to delete one by one / Press x to go to main menu${WHITE}"
read del
if [[ "$del" == "" ]]; then
echo -e "${RED}Please input something\n${GREEN}Press enter to continue "
read lol
continue
elif [[ "$del" == "x" ]]; then
loop
else
sed -i "${del}d" /sdcard/RemGaming/APPLIST.txt
echo -e "\n${RED}Deleted line $del successfully ${WHITE}\n\nPress enter to continue deleting or press x to goto main menu"
read any
if [[ "$any" == "x" ]]; then
loop
else
any=1
fi
fi
done
loop
;;
*) echo -e "\nWrong Choice! Please input Valid number and hit enter"
esac
 done

